# -*- coding: utf-8 -*-
"""Copy of intern task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWoJHshOpnTE8v3Q6UfvZfKchGIYhAkC
"""

#importing the required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

data=pd.read_csv('/content/housing.csv')#loading the dataset

data.info()

data.isnull()

data.describe()

varlist =['bedroom','bathroom','floors','sqft_living','street','city','view','waterfront']
def binary_map(x):
  return x.map({'yes': 1,"no":0})
  df[varlist]= df[varlist].apply(binary_map)

import pandas as pd

df = pd.read_csv("/content/housing.csv")

df.head()

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

!pip install pandas
import pandas as pd

print(data.shape)

print(data.head())

import pandas as pd

data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
status = pd.DataFrame(data)

status.head()

df.isnull().sum()

np.random.seed(0)
df_train, df_test = train_test_split (df, train_size=0.7, test_size=0.3, random_state=100)

from sklearn.preprocessing import StandardScaler

scaler =StandardScaler

